# Generated by Django 5.2.6 on 2025-09-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
